-- Compute: smallest warehouse, suspended after 60 s of inactivity
CREATE WAREHOUSE IF NOT EXISTS ENERGY_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- Storage: one database, one schema per layer
CREATE DATABASE IF NOT EXISTS ENERGY;
CREATE SCHEMA IF NOT EXISTS ENERGY.BRONZE;
CREATE SCHEMA IF NOT EXISTS ENERGY.SILVER;
CREATE SCHEMA IF NOT EXISTS ENERGY.GOLD;
