USE ROLE ACCOUNTADMIN;

-- Role for transformations (least privilege)
CREATE ROLE IF NOT EXISTS TRANSFORMER;
GRANT ROLE TRANSFORMER TO ROLE SYSADMIN;

GRANT USAGE ON WAREHOUSE ENERGY_WH TO ROLE TRANSFORMER;
GRANT USAGE ON DATABASE ENERGY TO ROLE TRANSFORMER;
GRANT ALL ON SCHEMA ENERGY.BRONZE TO ROLE TRANSFORMER;
GRANT ALL ON SCHEMA ENERGY.SILVER TO ROLE TRANSFORMER;
GRANT ALL ON SCHEMA ENERGY.GOLD   TO ROLE TRANSFORMER;
GRANT ALL ON ALL TABLES IN SCHEMA ENERGY.BRONZE TO ROLE TRANSFORMER;
GRANT READ, WRITE ON STAGE ENERGY.BRONZE.RAW_STAGE TO ROLE TRANSFORMER;
GRANT USAGE ON FILE FORMAT ENERGY.BRONZE.CSV_FORMAT TO ROLE TRANSFORMER;

-- Service user for scripts and dbt: key-pair authentication only, no password
CREATE USER IF NOT EXISTS DBT_USER
  TYPE = SERVICE
  DEFAULT_ROLE = TRANSFORMER
  DEFAULT_WAREHOUSE = ENERGY_WH
  RSA_PUBLIC_KEY = '<your_public_key>';

GRANT ROLE TRANSFORMER TO USER DBT_USER;
