USE WAREHOUSE ENERGY_WH;

-- 1. Raw series overview (Bronze)
SELECT PRODUCTION_TYPE, COUNT(*), ROUND(AVG(VALUE_MW)) AS avg_value
FROM ENERGY.BRONZE.RAW_POWER
GROUP BY 1 ORDER BY 1;

-- 2. Classification check (Silver)
SELECT PRODUCTION_TYPE, SERIES_TYPE, SOURCE_GROUP, UNIT, IS_RENEWABLE
FROM ENERGY.SILVER.STG_POWER
GROUP BY ALL
ORDER BY SERIES_TYPE, SOURCE_GROUP, PRODUCTION_TYPE;

-- 3. Key insight: renewables vs price (Gold)
SELECT
    ROUND(CORR(RENEWABLE_SHARE_PCT, PRICE_EUR_MWH), 2) AS correlation,
    COUNT_IF(IS_NEGATIVE_PRICE)                        AS negative_price_hours,
    ROUND(AVG(PRICE_EUR_MWH), 1)                       AS avg_price_eur_mwh
FROM ENERGY.GOLD.FCT_HOURLY_MARKET;
